// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: yat/v1/login.proto

package yatv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_yat_v1_login_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yat_v1_login_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_yat_v1_login_proto_rawDescGZIP(), []int{0}
}

type LoginResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*LoginResponse_Start
	//	*LoginResponse_Creds
	//	*LoginResponse_Error
	Event         isLoginResponse_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_yat_v1_login_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yat_v1_login_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_yat_v1_login_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetEvent() isLoginResponse_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *LoginResponse) GetStart() *LoginStart {
	if x != nil {
		if x, ok := x.Event.(*LoginResponse_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *LoginResponse) GetCreds() *LoginCreds {
	if x != nil {
		if x, ok := x.Event.(*LoginResponse_Creds); ok {
			return x.Creds
		}
	}
	return nil
}

func (x *LoginResponse) GetError() *LoginError {
	if x != nil {
		if x, ok := x.Event.(*LoginResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isLoginResponse_Event interface {
	isLoginResponse_Event()
}

type LoginResponse_Start struct {
	Start *LoginStart `protobuf:"bytes,1,opt,name=start,oneof"`
}

type LoginResponse_Creds struct {
	Creds *LoginCreds `protobuf:"bytes,2,opt,name=creds,oneof"`
}

type LoginResponse_Error struct {
	Error *LoginError `protobuf:"bytes,3,opt,name=error,oneof"`
}

func (*LoginResponse_Start) isLoginResponse_Event() {}

func (*LoginResponse_Creds) isLoginResponse_Event() {}

func (*LoginResponse_Error) isLoginResponse_Event() {}

type RefreshLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Refresh       *string                `protobuf:"bytes,1,opt,name=refresh" json:"refresh,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshLoginRequest) Reset() {
	*x = RefreshLoginRequest{}
	mi := &file_yat_v1_login_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshLoginRequest) ProtoMessage() {}

func (x *RefreshLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yat_v1_login_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshLoginRequest.ProtoReflect.Descriptor instead.
func (*RefreshLoginRequest) Descriptor() ([]byte, []int) {
	return file_yat_v1_login_proto_rawDescGZIP(), []int{2}
}

func (x *RefreshLoginRequest) GetRefresh() string {
	if x != nil && x.Refresh != nil {
		return *x.Refresh
	}
	return ""
}

type RefreshLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Creds         *LoginCreds            `protobuf:"bytes,1,opt,name=creds" json:"creds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshLoginResponse) Reset() {
	*x = RefreshLoginResponse{}
	mi := &file_yat_v1_login_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshLoginResponse) ProtoMessage() {}

func (x *RefreshLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yat_v1_login_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshLoginResponse.ProtoReflect.Descriptor instead.
func (*RefreshLoginResponse) Descriptor() ([]byte, []int) {
	return file_yat_v1_login_proto_rawDescGZIP(), []int{3}
}

func (x *RefreshLoginResponse) GetCreds() *LoginCreds {
	if x != nil {
		return x.Creds
	}
	return nil
}

type LoginStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           *string                `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginStart) Reset() {
	*x = LoginStart{}
	mi := &file_yat_v1_login_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginStart) ProtoMessage() {}

func (x *LoginStart) ProtoReflect() protoreflect.Message {
	mi := &file_yat_v1_login_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginStart.ProtoReflect.Descriptor instead.
func (*LoginStart) Descriptor() ([]byte, []int) {
	return file_yat_v1_login_proto_rawDescGZIP(), []int{4}
}

func (x *LoginStart) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

type LoginCreds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *string                `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Refresh       *string                `protobuf:"bytes,2,opt,name=refresh" json:"refresh,omitempty"`
	Expiry        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expiry" json:"expiry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginCreds) Reset() {
	*x = LoginCreds{}
	mi := &file_yat_v1_login_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginCreds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginCreds) ProtoMessage() {}

func (x *LoginCreds) ProtoReflect() protoreflect.Message {
	mi := &file_yat_v1_login_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginCreds.ProtoReflect.Descriptor instead.
func (*LoginCreds) Descriptor() ([]byte, []int) {
	return file_yat_v1_login_proto_rawDescGZIP(), []int{5}
}

func (x *LoginCreds) GetToken() string {
	if x != nil && x.Token != nil {
		return *x.Token
	}
	return ""
}

func (x *LoginCreds) GetRefresh() string {
	if x != nil && x.Refresh != nil {
		return *x.Refresh
	}
	return ""
}

func (x *LoginCreds) GetExpiry() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiry
	}
	return nil
}

type LoginError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *string                `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginError) Reset() {
	*x = LoginError{}
	mi := &file_yat_v1_login_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginError) ProtoMessage() {}

func (x *LoginError) ProtoReflect() protoreflect.Message {
	mi := &file_yat_v1_login_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginError.ProtoReflect.Descriptor instead.
func (*LoginError) Descriptor() ([]byte, []int) {
	return file_yat_v1_login_proto_rawDescGZIP(), []int{6}
}

func (x *LoginError) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

var File_yat_v1_login_proto protoreflect.FileDescriptor

const file_yat_v1_login_proto_rawDesc = "" +
	"\n" +
	"\x12yat/v1/login.proto\x12\x06yat.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x0e\n" +
	"\fLoginRequest\"\x9c\x01\n" +
	"\rLoginResponse\x12*\n" +
	"\x05start\x18\x01 \x01(\v2\x12.yat.v1.LoginStartH\x00R\x05start\x12*\n" +
	"\x05creds\x18\x02 \x01(\v2\x12.yat.v1.LoginCredsH\x00R\x05creds\x12*\n" +
	"\x05error\x18\x03 \x01(\v2\x12.yat.v1.LoginErrorH\x00R\x05errorB\a\n" +
	"\x05event\"/\n" +
	"\x13RefreshLoginRequest\x12\x18\n" +
	"\arefresh\x18\x01 \x01(\tR\arefresh\"@\n" +
	"\x14RefreshLoginResponse\x12(\n" +
	"\x05creds\x18\x01 \x01(\v2\x12.yat.v1.LoginCredsR\x05creds\"\x1e\n" +
	"\n" +
	"LoginStart\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"p\n" +
	"\n" +
	"LoginCreds\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x18\n" +
	"\arefresh\x18\x02 \x01(\tR\arefresh\x122\n" +
	"\x06expiry\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x06expiry\"&\n" +
	"\n" +
	"LoginError\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x95\x01\n" +
	"\fLoginService\x128\n" +
	"\x05Login\x12\x14.yat.v1.LoginRequest\x1a\x15.yat.v1.LoginResponse\"\x000\x01\x12K\n" +
	"\fRefreshLogin\x12\x1b.yat.v1.RefreshLoginRequest\x1a\x1c.yat.v1.RefreshLoginResponse\"\x00Bx\n" +
	"\n" +
	"com.yat.v1B\n" +
	"LoginProtoP\x01Z%yat.io/yat/internal/wire/yat/v1;yatv1\xa2\x02\x03YXX\xaa\x02\x06Yat.V1\xca\x02\x06Yat\\V1\xe2\x02\x12Yat\\V1\\GPBMetadata\xea\x02\aYat::V1b\beditionsp\xe8\a"

var (
	file_yat_v1_login_proto_rawDescOnce sync.Once
	file_yat_v1_login_proto_rawDescData []byte
)

func file_yat_v1_login_proto_rawDescGZIP() []byte {
	file_yat_v1_login_proto_rawDescOnce.Do(func() {
		file_yat_v1_login_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_yat_v1_login_proto_rawDesc), len(file_yat_v1_login_proto_rawDesc)))
	})
	return file_yat_v1_login_proto_rawDescData
}

var file_yat_v1_login_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_yat_v1_login_proto_goTypes = []any{
	(*LoginRequest)(nil),          // 0: yat.v1.LoginRequest
	(*LoginResponse)(nil),         // 1: yat.v1.LoginResponse
	(*RefreshLoginRequest)(nil),   // 2: yat.v1.RefreshLoginRequest
	(*RefreshLoginResponse)(nil),  // 3: yat.v1.RefreshLoginResponse
	(*LoginStart)(nil),            // 4: yat.v1.LoginStart
	(*LoginCreds)(nil),            // 5: yat.v1.LoginCreds
	(*LoginError)(nil),            // 6: yat.v1.LoginError
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_yat_v1_login_proto_depIdxs = []int32{
	4, // 0: yat.v1.LoginResponse.start:type_name -> yat.v1.LoginStart
	5, // 1: yat.v1.LoginResponse.creds:type_name -> yat.v1.LoginCreds
	6, // 2: yat.v1.LoginResponse.error:type_name -> yat.v1.LoginError
	5, // 3: yat.v1.RefreshLoginResponse.creds:type_name -> yat.v1.LoginCreds
	7, // 4: yat.v1.LoginCreds.expiry:type_name -> google.protobuf.Timestamp
	0, // 5: yat.v1.LoginService.Login:input_type -> yat.v1.LoginRequest
	2, // 6: yat.v1.LoginService.RefreshLogin:input_type -> yat.v1.RefreshLoginRequest
	1, // 7: yat.v1.LoginService.Login:output_type -> yat.v1.LoginResponse
	3, // 8: yat.v1.LoginService.RefreshLogin:output_type -> yat.v1.RefreshLoginResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_yat_v1_login_proto_init() }
func file_yat_v1_login_proto_init() {
	if File_yat_v1_login_proto != nil {
		return
	}
	file_yat_v1_login_proto_msgTypes[1].OneofWrappers = []any{
		(*LoginResponse_Start)(nil),
		(*LoginResponse_Creds)(nil),
		(*LoginResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_yat_v1_login_proto_rawDesc), len(file_yat_v1_login_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_yat_v1_login_proto_goTypes,
		DependencyIndexes: file_yat_v1_login_proto_depIdxs,
		MessageInfos:      file_yat_v1_login_proto_msgTypes,
	}.Build()
	File_yat_v1_login_proto = out.File
	file_yat_v1_login_proto_goTypes = nil
	file_yat_v1_login_proto_depIdxs = nil
}
