package yat

import "bytes"

//go:generate sh -c "ragel -Z -G2 -o path.rl.go path.rl && go fmt path.rl.go > /dev/null"

type Path struct {
	data []byte
}

// NewPath copies the given string into a new path.
// If the string can't be parsed, NewPath panics.
func NewPath(str string) Path {
	path, _, err := parsePath(str)
	if err != nil {
		panic(err)
	}

	return path
}

// ParsePath parses a path from a raw value.
// It returns an error if the path is invalid.
// If the path contains a * or ** wildcard, ParsePath returns wild=true.
func ParsePath(raw []byte) (parsed Path, wild bool, err error) {
	return parsePath(raw)
}

// Match returns true if the given path matches the receiver,
// which may contain * or ** wildcards.
// Zero values never match.
func (p Path) Match(o Path) bool {
	if p.IsZero() || o.IsZero() {
		return false
	}

	// head segments
	var ps, os Path

	for {
		ps, p = p.cut()
		os, o = o.cut()

		if ps.IsZero() {
			return os.IsZero()
		}

		if os.IsZero() {
			return false
		}

		switch ps.String() {
		case "*":
			continue

		case "**":
			return true

		default:
			if !os.Equal(ps) {
				return false
			}
		}
	}
}

// Clone returns a copy of the path.
func (p Path) Clone() Path {
	return Path{bytes.Clone(p.data)}
}

// String returns the path as a string.
func (p Path) String() string {
	return string(p.data)
}

// IsAtPath returns true if the path starts with "@".
// At-paths are generated by the server to receive responses.
func (p Path) IsAtPath() bool {
	return !p.IsZero() && p.data[0] == '@'
}

// IsSpecialPath returns true if the path starts with "$".
// Special paths are reserved for internal API and events.
func (p Path) IsSpecialPath() bool {
	return !p.IsZero() && p.data[0] == '$'
}

// IsZero returns true if the path is empty.
func (p Path) IsZero() bool {
	return len(p.data) == 0
}

// Equal returns true if the paths are the same.
func (p Path) Equal(other Path) bool {
	return bytes.Equal(p.data, other.data)
}

func (p Path) MarshalText() (text []byte, err error) {
	return bytes.Clone(p.data), nil
}

func (p *Path) UnmarshalText(text []byte) error {
	pp, _, err := ParsePath(bytes.Clone(text))
	if err != nil {
		return err
	}

	*p = pp
	return nil
}

// cut splits the path at the first /.
// car and cdr may be zero values.
func (p Path) cut() (car, cdr Path) {
	car.data, cdr.data, _ = bytes.Cut(p.data, []byte{'/'})
	return
}
