package yat

import (
	"bytes"
	"slices"
	"strings"
	"unsafe"
)

//go:generate sh -c "ragel -Z -G2 -o path.rl.go path.rl && go fmt path.rl.go > /dev/null"

type Path struct {
	s string
}

// MaxPathLen is the maximum length of a path in bytes.
const MaxPathLen = 4096

// NewPath parses the given string into a new path.
// If the string is not a valid path, NewPath panics.
func NewPath(str string) Path {
	path, err := ParsePath(str)
	if err != nil {
		panic(err)
	}

	return path
}

func unsafePath(b []byte) Path {
	return Path{unsafe.String(&b[0], len(b))}
}

// Match returns true if the given path matches the receiver,
// which may contain * or ** wildcards.
// Zero values never match.
func (p Path) Match(o Path) bool {
	if p.IsZero() || o.IsZero() {
		return false
	}

	// head segments
	var ps, os Path

	for {
		ps, p = p.cut()
		os, o = o.cut()

		if ps.IsZero() {
			return os.IsZero()
		}

		if os.IsZero() {
			return false
		}

		switch ps.String() {
		case "*":
			if os.s != "**" {
				continue
			}

		case "**":
			return true

		}

		if !os.Equal(ps) {
			return false
		}
	}
}

// Clone returns a copy of the path.
func (p Path) Clone() Path {
	return Path{strings.Clone(p.s)}
}

// String returns the path string.
func (p Path) String() string {
	return p.s
}

// IsWild returns true if the path contains a wildcard.
func (p Path) IsWild() bool {
	return slices.Index([]byte(p.s), '*') >= 0
}

// IsPostbox returns true if the path is an inbox generated by a router.
func (p Path) IsPostbox() bool {
	return strings.HasPrefix(p.s, "@")
}

// IsZero returns true if the path is empty.
func (p Path) IsZero() bool {
	return p.s == ""
}

// Equal returns true if the paths are the same.
func (p Path) Equal(other Path) bool {
	return other.s == p.s
}

func (p Path) MarshalText() (text []byte, err error) {
	return []byte(p.s), nil
}

func (p *Path) UnmarshalText(text []byte) error {
	pp, err := ParsePath(bytes.Clone(text))
	if err != nil {
		return err
	}

	*p = pp
	return nil
}

func (p Path) bytes() []byte {
	return unsafe.Slice(unsafe.StringData(p.s), len(p.s))
}

func (p Path) cut() (car, cdr Path) {
	car.s, cdr.s, _ = strings.Cut(p.s, "/")
	return
}
