package yat

import (
	"bytes"
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"encoding/binary"
	"slices"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	"github.com/google/uuid"

	msgv1 "yat.io/yat/internal/wire/msg/v1"
)

type Router struct {
	id uuid.UUID
	pk [16]byte
	mu sync.RWMutex
	rn rnode
}

type rnode struct {
	up   *rnode
	dn   map[string]*rnode
	name string
	ee   []*rent

	// cached for fast lookup
	wildElem, wildSuffix *rnode
}

type rsub struct {
	Sel
	Flags msgv1.SubFlags
}

type rent struct {
	rsub

	up *rnode
	f  func(m rmsg, final bool)
	n  atomic.Uint64
}

type rmsg struct {
	Msg
	frm []byte
}

// postboxTTL governs the lifetime of inboxes returned by newPostbox.
const postboxTTL = 90 * time.Minute

func NewRouter() *Router {
	rr := &Router{
		id: uuid.Must(uuid.NewRandom()),
	}

	// for postbox HMAC
	rand.Read(rr.pk[:])

	return rr
}

func (rr *Router) route(m Msg) []*rent {
	if m.Path.IsZero() {
		return nil
	}

	rr.mu.RLock()
	defer rr.mu.RUnlock()
	return slices.DeleteFunc(rr.rn.Match(m.Path), func(e *rent) bool {
		return e.IsHandler() && m.Inbox.IsZero()
	})
}

func (r *Router) deliver(ee []*rent, m rmsg) {
	var old []*rent
	for _, e := range ee {
		n := e.n.Add(1)
		lim := uint64(e.Sel.Limit)
		ltd := lim > 0 && n == lim
		if lim == 0 || n <= lim {
			e.f(m, ltd)
		}

		if ltd {
			old = append(old, e)
		}
	}

	if len(old) == 0 {
		return
	}

	r.mu.Lock()
	defer r.mu.Unlock()
	for _, e := range old {
		e.up.Del(e)
	}
}

func (r *Router) ins(sub rsub, f func(rmsg, bool)) *rent {
	r.mu.Lock()
	defer r.mu.Unlock()
	return r.rn.Ins(sub, f)
}

func (r *Router) del(e *rent) {
	r.mu.Lock()
	defer r.mu.Unlock()
	e.up.Del(e)
}

// newPostbox returns a unique inbox path signed by the router.
// validPostbox will return true for this path until [postboxTTL] is exceed.
func (r *Router) newPostbox() Path {
	var tok [32]byte

	// nonce
	rand.Read(tok[:8])

	// expiry
	binary.LittleEndian.PutUint64(tok[8:16],
		uint64(time.Now().Add(postboxTTL).Unix()))

	mac := hmac.New(sha256.New, r.pk[:])
	_, _ = mac.Write(tok[:16])
	copy(tok[16:], mac.Sum(nil))

	p := []byte("@")
	p = base64.RawURLEncoding.AppendEncode(p, r.id[:])
	p = append(p, '/')
	p = base64.RawURLEncoding.AppendEncode(p, tok[:])

	return unsafePath(p)
}

// validPostbox returns true if inbox was recently generated by newPostbox.
// It returns false if the inbox is malformed, foreign, or too old.
func (r *Router) validPostbox(inbox Path) bool {
	if len(inbox.s) < 2 {
		return false
	}

	if inbox.s[0] != '@' {
		return false
	}

	inbox.s = inbox.s[1:]
	b64id, b64sig, _ := strings.Cut(inbox.s, "/")

	id, err := base64.RawURLEncoding.DecodeString(b64id)
	if err != nil {
		return false
	}

	sig, err := base64.RawURLEncoding.DecodeString(b64sig)
	if err != nil {
		return false
	}

	if !bytes.Equal(id, r.id[:]) {
		return false
	}

	if len(sig) != 32 {
		return false
	}

	mac := hmac.New(sha256.New, r.pk[:])
	mac.Write(sig[:16])

	if !hmac.Equal(sig[16:], mac.Sum(nil)[:16]) {
		return false
	}

	exp := binary.LittleEndian.Uint64(sig[8:16])
	return exp >= uint64(time.Now().Unix())
}

// Ins inserts an entry into the tree.
// Calls to Match will consider the entry.
func (n *rnode) Ins(sub rsub, f func(rmsg, bool)) *rent {
	up := n.leaf(sub.Path, true)
	e := &rent{
		rsub: sub,
		up:   up,
		f:    f,
	}

	up.ee = append(up.ee, e)
	return e
}

// Match returns the entries with patterns matching p.
func (n *rnode) Match(p Path) []*rent {
	var ee []*rent
	n.match(&ee, p, p.IsPostbox())
	return ee
}

// Del deletes the given child entry.
// n is pruned if it is empty after e is deleted.
func (n *rnode) Del(e *rent) {
	i := slices.Index(n.ee, e)
	if i < 0 {
		return
	}

	j := len(n.ee) - 1

	// overwrite
	n.ee[i] = n.ee[j]
	n.ee[j] = nil

	// trim
	n.ee = n.ee[:j]

	// prune empty branches
	if len(n.dn) == 0 && len(n.ee) == 0 {
		ancestor := n.up
		name := n.name

		for ancestor.up != nil && len(ancestor.dn) == 1 && len(ancestor.ee) == 0 {
			name = ancestor.name
			ancestor = ancestor.up
		}

		delete(ancestor.dn, name)
		switch name {
		case "*":
			ancestor.wildElem = nil

		case "**":
			ancestor.wildSuffix = nil
		}
	}
}

func (n *rnode) leaf(p Path, createMissing bool) *rnode {
	car, cdr := p.cut()
	if car.IsZero() {
		return n
	}

	name := car.String()

	var c *rnode
	switch name {
	case "*":
		c = n.wildElem

	case "**":
		c = n.wildSuffix

	default:
		c = n.dn[name]
	}

	if c != nil {
		return c.leaf(cdr, createMissing)
	}

	if !createMissing {
		return nil
	}

	if n.dn == nil {
		n.dn = make(map[string]*rnode)
	}

	c = &rnode{
		up:   n,
		name: name,
	}

	n.dn[name] = c
	switch name {
	case "*":
		n.wildElem = c

	case "**":
		n.wildSuffix = c
	}

	return c.leaf(cdr, true)
}

func (n *rnode) match(ee *[]*rent, p Path, exact bool) {
	if p.IsZero() {
		*ee = append(*ee, n.ee...)
		return
	}

	car, cdr := p.cut()
	if c, ok := n.dn[car.String()]; ok {
		c.match(ee, cdr, exact)
	}

	if !exact {
		if n.wildSuffix != nil {
			n.wildSuffix.match(ee, Path{}, false)
		}

		if n.wildElem != nil {
			n.wildElem.match(ee, cdr, false)
		}
	}
}

func (e *rent) IsHandler() bool {
	return e.Flags&msgv1.SubFlags_SUB_FLAGS_HANDLER > 0
}
