// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: msg/v1/msg.proto

package msgv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PubRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          []byte                 `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	Inbox         []byte                 `protobuf:"bytes,3,opt,name=inbox" json:"inbox,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PubRequest) Reset() {
	*x = PubRequest{}
	mi := &file_msg_v1_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PubRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubRequest) ProtoMessage() {}

func (x *PubRequest) ProtoReflect() protoreflect.Message {
	mi := &file_msg_v1_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubRequest.ProtoReflect.Descriptor instead.
func (*PubRequest) Descriptor() ([]byte, []int) {
	return file_msg_v1_msg_proto_rawDescGZIP(), []int{0}
}

func (x *PubRequest) GetPath() []byte {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *PubRequest) GetInbox() []byte {
	if x != nil {
		return x.Inbox
	}
	return nil
}

func (x *PubRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PubResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PubResponse) Reset() {
	*x = PubResponse{}
	mi := &file_msg_v1_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PubResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubResponse) ProtoMessage() {}

func (x *PubResponse) ProtoReflect() protoreflect.Message {
	mi := &file_msg_v1_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubResponse.ProtoReflect.Descriptor instead.
func (*PubResponse) Descriptor() ([]byte, []int) {
	return file_msg_v1_msg_proto_rawDescGZIP(), []int{1}
}

type MpubRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ack           *int64                 `protobuf:"varint,1,opt,name=ack" json:"ack,omitempty"`
	Path          []byte                 `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	Inbox         []byte                 `protobuf:"bytes,3,opt,name=inbox" json:"inbox,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MpubRequest) Reset() {
	*x = MpubRequest{}
	mi := &file_msg_v1_msg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MpubRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MpubRequest) ProtoMessage() {}

func (x *MpubRequest) ProtoReflect() protoreflect.Message {
	mi := &file_msg_v1_msg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MpubRequest.ProtoReflect.Descriptor instead.
func (*MpubRequest) Descriptor() ([]byte, []int) {
	return file_msg_v1_msg_proto_rawDescGZIP(), []int{2}
}

func (x *MpubRequest) GetAck() int64 {
	if x != nil && x.Ack != nil {
		return *x.Ack
	}
	return 0
}

func (x *MpubRequest) GetPath() []byte {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *MpubRequest) GetInbox() []byte {
	if x != nil {
		return x.Inbox
	}
	return nil
}

func (x *MpubRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type MpubResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ack           *int64                 `protobuf:"varint,1,opt,name=ack" json:"ack,omitempty"`
	Status        *int32                 `protobuf:"varint,7,opt,name=status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MpubResponse) Reset() {
	*x = MpubResponse{}
	mi := &file_msg_v1_msg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MpubResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MpubResponse) ProtoMessage() {}

func (x *MpubResponse) ProtoReflect() protoreflect.Message {
	mi := &file_msg_v1_msg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MpubResponse.ProtoReflect.Descriptor instead.
func (*MpubResponse) Descriptor() ([]byte, []int) {
	return file_msg_v1_msg_proto_rawDescGZIP(), []int{3}
}

func (x *MpubResponse) GetAck() int64 {
	if x != nil && x.Ack != nil {
		return *x.Ack
	}
	return 0
}

func (x *MpubResponse) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

type EmitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          []byte                 `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	Inbox         []byte                 `protobuf:"bytes,3,opt,name=inbox" json:"inbox,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitRequest) Reset() {
	*x = EmitRequest{}
	mi := &file_msg_v1_msg_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitRequest) ProtoMessage() {}

func (x *EmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_msg_v1_msg_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitRequest.ProtoReflect.Descriptor instead.
func (*EmitRequest) Descriptor() ([]byte, []int) {
	return file_msg_v1_msg_proto_rawDescGZIP(), []int{4}
}

func (x *EmitRequest) GetPath() []byte {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *EmitRequest) GetInbox() []byte {
	if x != nil {
		return x.Inbox
	}
	return nil
}

func (x *EmitRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type EmitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitResponse) Reset() {
	*x = EmitResponse{}
	mi := &file_msg_v1_msg_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitResponse) ProtoMessage() {}

func (x *EmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_msg_v1_msg_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitResponse.ProtoReflect.Descriptor instead.
func (*EmitResponse) Descriptor() ([]byte, []int) {
	return file_msg_v1_msg_proto_rawDescGZIP(), []int{5}
}

type PostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          []byte                 `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data" json:"data,omitempty"`
	Limit         *int64                 `protobuf:"varint,6,opt,name=limit" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostRequest) Reset() {
	*x = PostRequest{}
	mi := &file_msg_v1_msg_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostRequest) ProtoMessage() {}

func (x *PostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_msg_v1_msg_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostRequest.ProtoReflect.Descriptor instead.
func (*PostRequest) Descriptor() ([]byte, []int) {
	return file_msg_v1_msg_proto_rawDescGZIP(), []int{6}
}

func (x *PostRequest) GetPath() []byte {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *PostRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PostRequest) GetLimit() int64 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

type PostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inbox         []byte                 `protobuf:"bytes,3,opt,name=inbox" json:"inbox,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostResponse) Reset() {
	*x = PostResponse{}
	mi := &file_msg_v1_msg_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostResponse) ProtoMessage() {}

func (x *PostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_msg_v1_msg_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostResponse.ProtoReflect.Descriptor instead.
func (*PostResponse) Descriptor() ([]byte, []int) {
	return file_msg_v1_msg_proto_rawDescGZIP(), []int{7}
}

func (x *PostResponse) GetInbox() []byte {
	if x != nil {
		return x.Inbox
	}
	return nil
}

func (x *PostResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SubRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          []byte                 `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	Limit         *int64                 `protobuf:"varint,6,opt,name=limit" json:"limit,omitempty"`
	Handler       *bool                  `protobuf:"varint,8,opt,name=handler" json:"handler,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubRequest) Reset() {
	*x = SubRequest{}
	mi := &file_msg_v1_msg_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubRequest) ProtoMessage() {}

func (x *SubRequest) ProtoReflect() protoreflect.Message {
	mi := &file_msg_v1_msg_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubRequest.ProtoReflect.Descriptor instead.
func (*SubRequest) Descriptor() ([]byte, []int) {
	return file_msg_v1_msg_proto_rawDescGZIP(), []int{8}
}

func (x *SubRequest) GetPath() []byte {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *SubRequest) GetLimit() int64 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *SubRequest) GetHandler() bool {
	if x != nil && x.Handler != nil {
		return *x.Handler
	}
	return false
}

type SubResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          []byte                 `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	Inbox         []byte                 `protobuf:"bytes,3,opt,name=inbox" json:"inbox,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data" json:"data,omitempty"`
	Uuid          []byte                 `protobuf:"bytes,5,opt,name=uuid" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubResponse) Reset() {
	*x = SubResponse{}
	mi := &file_msg_v1_msg_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubResponse) ProtoMessage() {}

func (x *SubResponse) ProtoReflect() protoreflect.Message {
	mi := &file_msg_v1_msg_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubResponse.ProtoReflect.Descriptor instead.
func (*SubResponse) Descriptor() ([]byte, []int) {
	return file_msg_v1_msg_proto_rawDescGZIP(), []int{9}
}

func (x *SubResponse) GetPath() []byte {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *SubResponse) GetInbox() []byte {
	if x != nil {
		return x.Inbox
	}
	return nil
}

func (x *SubResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SubResponse) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

var File_msg_v1_msg_proto protoreflect.FileDescriptor

const file_msg_v1_msg_proto_rawDesc = "" +
	"\n" +
	"\x10msg/v1/msg.proto\x12\x06msg.v1\"J\n" +
	"\n" +
	"PubRequest\x12\x12\n" +
	"\x04path\x18\x02 \x01(\fR\x04path\x12\x14\n" +
	"\x05inbox\x18\x03 \x01(\fR\x05inbox\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"\r\n" +
	"\vPubResponse\"]\n" +
	"\vMpubRequest\x12\x10\n" +
	"\x03ack\x18\x01 \x01(\x03R\x03ack\x12\x12\n" +
	"\x04path\x18\x02 \x01(\fR\x04path\x12\x14\n" +
	"\x05inbox\x18\x03 \x01(\fR\x05inbox\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"8\n" +
	"\fMpubResponse\x12\x10\n" +
	"\x03ack\x18\x01 \x01(\x03R\x03ack\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\"K\n" +
	"\vEmitRequest\x12\x12\n" +
	"\x04path\x18\x02 \x01(\fR\x04path\x12\x14\n" +
	"\x05inbox\x18\x03 \x01(\fR\x05inbox\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"\x0e\n" +
	"\fEmitResponse\"K\n" +
	"\vPostRequest\x12\x12\n" +
	"\x04path\x18\x02 \x01(\fR\x04path\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x03R\x05limit\"8\n" +
	"\fPostResponse\x12\x14\n" +
	"\x05inbox\x18\x03 \x01(\fR\x05inbox\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"P\n" +
	"\n" +
	"SubRequest\x12\x12\n" +
	"\x04path\x18\x02 \x01(\fR\x04path\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x03R\x05limit\x12\x18\n" +
	"\ahandler\x18\b \x01(\bR\ahandler\"_\n" +
	"\vSubResponse\x12\x12\n" +
	"\x04path\x18\x02 \x01(\fR\x04path\x12\x14\n" +
	"\x05inbox\x18\x03 \x01(\fR\x05inbox\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x12\n" +
	"\x04uuid\x18\x05 \x01(\fR\x04uuid2\x99\x02\n" +
	"\n" +
	"MsgService\x120\n" +
	"\x03Pub\x12\x12.msg.v1.PubRequest\x1a\x13.msg.v1.PubResponse\"\x00\x127\n" +
	"\x04Mpub\x12\x13.msg.v1.MpubRequest\x1a\x14.msg.v1.MpubResponse\"\x00(\x010\x01\x125\n" +
	"\x04Emit\x12\x13.msg.v1.EmitRequest\x1a\x14.msg.v1.EmitResponse\"\x00(\x01\x125\n" +
	"\x04Post\x12\x13.msg.v1.PostRequest\x1a\x14.msg.v1.PostResponse\"\x000\x01\x122\n" +
	"\x03Sub\x12\x12.msg.v1.SubRequest\x1a\x13.msg.v1.SubResponse\"\x000\x01Bv\n" +
	"\n" +
	"com.msg.v1B\bMsgProtoP\x01Z%yat.io/yat/internal/wire/msg/v1;msgv1\xa2\x02\x03MXX\xaa\x02\x06Msg.V1\xca\x02\x06Msg\\V1\xe2\x02\x12Msg\\V1\\GPBMetadata\xea\x02\aMsg::V1b\beditionsp\xe8\a"

var (
	file_msg_v1_msg_proto_rawDescOnce sync.Once
	file_msg_v1_msg_proto_rawDescData []byte
)

func file_msg_v1_msg_proto_rawDescGZIP() []byte {
	file_msg_v1_msg_proto_rawDescOnce.Do(func() {
		file_msg_v1_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_msg_v1_msg_proto_rawDesc), len(file_msg_v1_msg_proto_rawDesc)))
	})
	return file_msg_v1_msg_proto_rawDescData
}

var file_msg_v1_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_msg_v1_msg_proto_goTypes = []any{
	(*PubRequest)(nil),   // 0: msg.v1.PubRequest
	(*PubResponse)(nil),  // 1: msg.v1.PubResponse
	(*MpubRequest)(nil),  // 2: msg.v1.MpubRequest
	(*MpubResponse)(nil), // 3: msg.v1.MpubResponse
	(*EmitRequest)(nil),  // 4: msg.v1.EmitRequest
	(*EmitResponse)(nil), // 5: msg.v1.EmitResponse
	(*PostRequest)(nil),  // 6: msg.v1.PostRequest
	(*PostResponse)(nil), // 7: msg.v1.PostResponse
	(*SubRequest)(nil),   // 8: msg.v1.SubRequest
	(*SubResponse)(nil),  // 9: msg.v1.SubResponse
}
var file_msg_v1_msg_proto_depIdxs = []int32{
	0, // 0: msg.v1.MsgService.Pub:input_type -> msg.v1.PubRequest
	2, // 1: msg.v1.MsgService.Mpub:input_type -> msg.v1.MpubRequest
	4, // 2: msg.v1.MsgService.Emit:input_type -> msg.v1.EmitRequest
	6, // 3: msg.v1.MsgService.Post:input_type -> msg.v1.PostRequest
	8, // 4: msg.v1.MsgService.Sub:input_type -> msg.v1.SubRequest
	1, // 5: msg.v1.MsgService.Pub:output_type -> msg.v1.PubResponse
	3, // 6: msg.v1.MsgService.Mpub:output_type -> msg.v1.MpubResponse
	5, // 7: msg.v1.MsgService.Emit:output_type -> msg.v1.EmitResponse
	7, // 8: msg.v1.MsgService.Post:output_type -> msg.v1.PostResponse
	9, // 9: msg.v1.MsgService.Sub:output_type -> msg.v1.SubResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_msg_v1_msg_proto_init() }
func file_msg_v1_msg_proto_init() {
	if File_msg_v1_msg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_msg_v1_msg_proto_rawDesc), len(file_msg_v1_msg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_msg_v1_msg_proto_goTypes,
		DependencyIndexes: file_msg_v1_msg_proto_depIdxs,
		MessageInfos:      file_msg_v1_msg_proto_msgTypes,
	}.Build()
	File_msg_v1_msg_proto = out.File
	file_msg_v1_msg_proto_goTypes = nil
	file_msg_v1_msg_proto_depIdxs = nil
}
