// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: msg/v1/msg.proto

package msgv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MsgService_Pub_FullMethodName  = "/msg.v1.MsgService/Pub"
	MsgService_Mpub_FullMethodName = "/msg.v1.MsgService/Mpub"
	MsgService_Emit_FullMethodName = "/msg.v1.MsgService/Emit"
	MsgService_Post_FullMethodName = "/msg.v1.MsgService/Post"
	MsgService_Sub_FullMethodName  = "/msg.v1.MsgService/Sub"
)

// MsgServiceClient is the client API for MsgService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MsgServiceClient interface {
	// Pub publishes a message.
	Pub(ctx context.Context, in *PubRequest, opts ...grpc.CallOption) (*PubResponse, error)
	// Mpub publishes a stream of messages
	// and receives a stream of corresponding responses.
	Mpub(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MpubRequest, MpubResponse], error)
	// Emit publishes a stream of messages without waiting for a response.
	Emit(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[EmitRequest, EmitResponse], error)
	// Post publishes a message and receives a stream of responses.
	// At least one interested subscriber must be flagged as a handler
	// for the message to be published. If there are no handlers,
	// the stream fails with status UNAVAILABLE.
	//
	// (A handler flag means a subscriber will try to reply
	// to every message it receives.)
	//
	// The limit field controls the number of responses
	// delivered to the post's server-generated inbox.
	// If the limit is 0, the number of responses is unlimited.
	Post(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PostResponse], error)
	// Sub subscribes to a stream of published messages.
	Sub(ctx context.Context, in *SubRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubResponse], error)
}

type msgServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgServiceClient(cc grpc.ClientConnInterface) MsgServiceClient {
	return &msgServiceClient{cc}
}

func (c *msgServiceClient) Pub(ctx context.Context, in *PubRequest, opts ...grpc.CallOption) (*PubResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PubResponse)
	err := c.cc.Invoke(ctx, MsgService_Pub_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) Mpub(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MpubRequest, MpubResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MsgService_ServiceDesc.Streams[0], MsgService_Mpub_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MpubRequest, MpubResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MsgService_MpubClient = grpc.BidiStreamingClient[MpubRequest, MpubResponse]

func (c *msgServiceClient) Emit(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[EmitRequest, EmitResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MsgService_ServiceDesc.Streams[1], MsgService_Emit_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EmitRequest, EmitResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MsgService_EmitClient = grpc.ClientStreamingClient[EmitRequest, EmitResponse]

func (c *msgServiceClient) Post(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PostResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MsgService_ServiceDesc.Streams[2], MsgService_Post_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PostRequest, PostResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MsgService_PostClient = grpc.ServerStreamingClient[PostResponse]

func (c *msgServiceClient) Sub(ctx context.Context, in *SubRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MsgService_ServiceDesc.Streams[3], MsgService_Sub_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubRequest, SubResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MsgService_SubClient = grpc.ServerStreamingClient[SubResponse]

// MsgServiceServer is the server API for MsgService service.
// All implementations must embed UnimplementedMsgServiceServer
// for forward compatibility.
type MsgServiceServer interface {
	// Pub publishes a message.
	Pub(context.Context, *PubRequest) (*PubResponse, error)
	// Mpub publishes a stream of messages
	// and receives a stream of corresponding responses.
	Mpub(grpc.BidiStreamingServer[MpubRequest, MpubResponse]) error
	// Emit publishes a stream of messages without waiting for a response.
	Emit(grpc.ClientStreamingServer[EmitRequest, EmitResponse]) error
	// Post publishes a message and receives a stream of responses.
	// At least one interested subscriber must be flagged as a handler
	// for the message to be published. If there are no handlers,
	// the stream fails with status UNAVAILABLE.
	//
	// (A handler flag means a subscriber will try to reply
	// to every message it receives.)
	//
	// The limit field controls the number of responses
	// delivered to the post's server-generated inbox.
	// If the limit is 0, the number of responses is unlimited.
	Post(*PostRequest, grpc.ServerStreamingServer[PostResponse]) error
	// Sub subscribes to a stream of published messages.
	Sub(*SubRequest, grpc.ServerStreamingServer[SubResponse]) error
	mustEmbedUnimplementedMsgServiceServer()
}

// UnimplementedMsgServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMsgServiceServer struct{}

func (UnimplementedMsgServiceServer) Pub(context.Context, *PubRequest) (*PubResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Pub not implemented")
}
func (UnimplementedMsgServiceServer) Mpub(grpc.BidiStreamingServer[MpubRequest, MpubResponse]) error {
	return status.Error(codes.Unimplemented, "method Mpub not implemented")
}
func (UnimplementedMsgServiceServer) Emit(grpc.ClientStreamingServer[EmitRequest, EmitResponse]) error {
	return status.Error(codes.Unimplemented, "method Emit not implemented")
}
func (UnimplementedMsgServiceServer) Post(*PostRequest, grpc.ServerStreamingServer[PostResponse]) error {
	return status.Error(codes.Unimplemented, "method Post not implemented")
}
func (UnimplementedMsgServiceServer) Sub(*SubRequest, grpc.ServerStreamingServer[SubResponse]) error {
	return status.Error(codes.Unimplemented, "method Sub not implemented")
}
func (UnimplementedMsgServiceServer) mustEmbedUnimplementedMsgServiceServer() {}
func (UnimplementedMsgServiceServer) testEmbeddedByValue()                    {}

// UnsafeMsgServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServiceServer will
// result in compilation errors.
type UnsafeMsgServiceServer interface {
	mustEmbedUnimplementedMsgServiceServer()
}

func RegisterMsgServiceServer(s grpc.ServiceRegistrar, srv MsgServiceServer) {
	// If the following call panics, it indicates UnimplementedMsgServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MsgService_ServiceDesc, srv)
}

func _MsgService_Pub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PubRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).Pub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MsgService_Pub_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).Pub(ctx, req.(*PubRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_Mpub_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MsgServiceServer).Mpub(&grpc.GenericServerStream[MpubRequest, MpubResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MsgService_MpubServer = grpc.BidiStreamingServer[MpubRequest, MpubResponse]

func _MsgService_Emit_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MsgServiceServer).Emit(&grpc.GenericServerStream[EmitRequest, EmitResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MsgService_EmitServer = grpc.ClientStreamingServer[EmitRequest, EmitResponse]

func _MsgService_Post_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PostRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MsgServiceServer).Post(m, &grpc.GenericServerStream[PostRequest, PostResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MsgService_PostServer = grpc.ServerStreamingServer[PostResponse]

func _MsgService_Sub_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MsgServiceServer).Sub(m, &grpc.GenericServerStream[SubRequest, SubResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MsgService_SubServer = grpc.ServerStreamingServer[SubResponse]

// MsgService_ServiceDesc is the grpc.ServiceDesc for MsgService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MsgService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "msg.v1.MsgService",
	HandlerType: (*MsgServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Pub",
			Handler:    _MsgService_Pub_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Mpub",
			Handler:       _MsgService_Mpub_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Emit",
			Handler:       _MsgService_Emit_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Post",
			Handler:       _MsgService_Post_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Sub",
			Handler:       _MsgService_Sub_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "msg/v1/msg.proto",
}
