// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: frames.proto

package wire

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This proto is just for reference. PubFrame and MsgFrame share field
// numbers to help the server avoid allocating memory on fanout.
// The field numbers match the *Field consts in protocol.go.
type SharedFields struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Num           uint64                 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	Path          []byte                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Inbox         []byte                 `protobuf:"bytes,4,opt,name=inbox,proto3" json:"inbox,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SharedFields) Reset() {
	*x = SharedFields{}
	mi := &file_frames_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SharedFields) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SharedFields) ProtoMessage() {}

func (x *SharedFields) ProtoReflect() protoreflect.Message {
	mi := &file_frames_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SharedFields.ProtoReflect.Descriptor instead.
func (*SharedFields) Descriptor() ([]byte, []int) {
	return file_frames_proto_rawDescGZIP(), []int{0}
}

func (x *SharedFields) GetNum() uint64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *SharedFields) GetPath() []byte {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *SharedFields) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SharedFields) GetInbox() []byte {
	if x != nil {
		return x.Inbox
	}
	return nil
}

type PubFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          []byte                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Inbox         []byte                 `protobuf:"bytes,4,opt,name=inbox,proto3" json:"inbox,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PubFrame) Reset() {
	*x = PubFrame{}
	mi := &file_frames_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PubFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubFrame) ProtoMessage() {}

func (x *PubFrame) ProtoReflect() protoreflect.Message {
	mi := &file_frames_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubFrame.ProtoReflect.Descriptor instead.
func (*PubFrame) Descriptor() ([]byte, []int) {
	return file_frames_proto_rawDescGZIP(), []int{1}
}

func (x *PubFrame) GetPath() []byte {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *PubFrame) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PubFrame) GetInbox() []byte {
	if x != nil {
		return x.Inbox
	}
	return nil
}

type SubFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Num           uint64                 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	Path          []byte                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Group         []byte                 `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	Limit         int64                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubFrame) Reset() {
	*x = SubFrame{}
	mi := &file_frames_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubFrame) ProtoMessage() {}

func (x *SubFrame) ProtoReflect() protoreflect.Message {
	mi := &file_frames_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubFrame.ProtoReflect.Descriptor instead.
func (*SubFrame) Descriptor() ([]byte, []int) {
	return file_frames_proto_rawDescGZIP(), []int{2}
}

func (x *SubFrame) GetNum() uint64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *SubFrame) GetPath() []byte {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *SubFrame) GetGroup() []byte {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *SubFrame) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type UnsubFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Num           uint64                 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubFrame) Reset() {
	*x = UnsubFrame{}
	mi := &file_frames_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubFrame) ProtoMessage() {}

func (x *UnsubFrame) ProtoReflect() protoreflect.Message {
	mi := &file_frames_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubFrame.ProtoReflect.Descriptor instead.
func (*UnsubFrame) Descriptor() ([]byte, []int) {
	return file_frames_proto_rawDescGZIP(), []int{3}
}

func (x *UnsubFrame) GetNum() uint64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type MsgFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Num           uint64                 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	Path          []byte                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Inbox         []byte                 `protobuf:"bytes,4,opt,name=inbox,proto3" json:"inbox,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgFrame) Reset() {
	*x = MsgFrame{}
	mi := &file_frames_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgFrame) ProtoMessage() {}

func (x *MsgFrame) ProtoReflect() protoreflect.Message {
	mi := &file_frames_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgFrame.ProtoReflect.Descriptor instead.
func (*MsgFrame) Descriptor() ([]byte, []int) {
	return file_frames_proto_rawDescGZIP(), []int{4}
}

func (x *MsgFrame) GetNum() uint64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *MsgFrame) GetPath() []byte {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *MsgFrame) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MsgFrame) GetInbox() []byte {
	if x != nil {
		return x.Inbox
	}
	return nil
}

var File_frames_proto protoreflect.FileDescriptor

const file_frames_proto_rawDesc = "" +
	"\n" +
	"\fframes.proto\x12\x03yat\"^\n" +
	"\fSharedFields\x12\x10\n" +
	"\x03num\x18\x01 \x01(\x04R\x03num\x12\x12\n" +
	"\x04path\x18\x02 \x01(\fR\x04path\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x14\n" +
	"\x05inbox\x18\x04 \x01(\fR\x05inbox\"N\n" +
	"\bPubFrame\x12\x12\n" +
	"\x04path\x18\x02 \x01(\fR\x04path\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x14\n" +
	"\x05inbox\x18\x04 \x01(\fR\x05inboxJ\x04\b\x01\x10\x02\"\\\n" +
	"\bSubFrame\x12\x10\n" +
	"\x03num\x18\x01 \x01(\x04R\x03num\x12\x12\n" +
	"\x04path\x18\x02 \x01(\fR\x04path\x12\x14\n" +
	"\x05group\x18\x03 \x01(\fR\x05group\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x03R\x05limit\"\x1e\n" +
	"\n" +
	"UnsubFrame\x12\x10\n" +
	"\x03num\x18\x01 \x01(\x04R\x03num\"Z\n" +
	"\bMsgFrame\x12\x10\n" +
	"\x03num\x18\x01 \x01(\x04R\x03num\x12\x12\n" +
	"\x04path\x18\x02 \x01(\fR\x04path\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x14\n" +
	"\x05inbox\x18\x04 \x01(\fR\x05inboxB\x11Z\x0fyat.io/yat/wireb\x06proto3"

var (
	file_frames_proto_rawDescOnce sync.Once
	file_frames_proto_rawDescData []byte
)

func file_frames_proto_rawDescGZIP() []byte {
	file_frames_proto_rawDescOnce.Do(func() {
		file_frames_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_frames_proto_rawDesc), len(file_frames_proto_rawDesc)))
	})
	return file_frames_proto_rawDescData
}

var file_frames_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_frames_proto_goTypes = []any{
	(*SharedFields)(nil), // 0: yat.SharedFields
	(*PubFrame)(nil),     // 1: yat.PubFrame
	(*SubFrame)(nil),     // 2: yat.SubFrame
	(*UnsubFrame)(nil),   // 3: yat.UnsubFrame
	(*MsgFrame)(nil),     // 4: yat.MsgFrame
}
var file_frames_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_frames_proto_init() }
func file_frames_proto_init() {
	if File_frames_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_frames_proto_rawDesc), len(file_frames_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_frames_proto_goTypes,
		DependencyIndexes: file_frames_proto_depIdxs,
		MessageInfos:      file_frames_proto_msgTypes,
	}.Build()
	File_frames_proto = out.File
	file_frames_proto_goTypes = nil
	file_frames_proto_depIdxs = nil
}
