// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: frames.proto

package wire

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// pub and msg
type Msg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Num           uint64                 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	Path          []byte                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Inbox         []byte                 `protobuf:"bytes,4,opt,name=inbox,proto3" json:"inbox,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Msg) Reset() {
	*x = Msg{}
	mi := &file_frames_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg) ProtoMessage() {}

func (x *Msg) ProtoReflect() protoreflect.Message {
	mi := &file_frames_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg.ProtoReflect.Descriptor instead.
func (*Msg) Descriptor() ([]byte, []int) {
	return file_frames_proto_rawDescGZIP(), []int{0}
}

func (x *Msg) GetNum() uint64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *Msg) GetPath() []byte {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *Msg) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Msg) GetInbox() []byte {
	if x != nil {
		return x.Inbox
	}
	return nil
}

type SubFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Num           uint64                 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	Path          []byte                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Group         []byte                 `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	Limit         int64                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Flags         uint64                 `protobuf:"varint,5,opt,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubFrame) Reset() {
	*x = SubFrame{}
	mi := &file_frames_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubFrame) ProtoMessage() {}

func (x *SubFrame) ProtoReflect() protoreflect.Message {
	mi := &file_frames_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubFrame.ProtoReflect.Descriptor instead.
func (*SubFrame) Descriptor() ([]byte, []int) {
	return file_frames_proto_rawDescGZIP(), []int{1}
}

func (x *SubFrame) GetNum() uint64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *SubFrame) GetPath() []byte {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *SubFrame) GetGroup() []byte {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *SubFrame) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SubFrame) GetFlags() uint64 {
	if x != nil {
		return x.Flags
	}
	return 0
}

type UnsubFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Num           uint64                 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubFrame) Reset() {
	*x = UnsubFrame{}
	mi := &file_frames_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubFrame) ProtoMessage() {}

func (x *UnsubFrame) ProtoReflect() protoreflect.Message {
	mi := &file_frames_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubFrame.ProtoReflect.Descriptor instead.
func (*UnsubFrame) Descriptor() ([]byte, []int) {
	return file_frames_proto_rawDescGZIP(), []int{2}
}

func (x *UnsubFrame) GetNum() uint64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type StatusFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Num           uint64                 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	Status        uint64                 `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusFrame) Reset() {
	*x = StatusFrame{}
	mi := &file_frames_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusFrame) ProtoMessage() {}

func (x *StatusFrame) ProtoReflect() protoreflect.Message {
	mi := &file_frames_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusFrame.ProtoReflect.Descriptor instead.
func (*StatusFrame) Descriptor() ([]byte, []int) {
	return file_frames_proto_rawDescGZIP(), []int{3}
}

func (x *StatusFrame) GetNum() uint64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *StatusFrame) GetStatus() uint64 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_frames_proto protoreflect.FileDescriptor

const file_frames_proto_rawDesc = "" +
	"\n" +
	"\fframes.proto\x12\x03yat\"U\n" +
	"\x03Msg\x12\x10\n" +
	"\x03num\x18\x01 \x01(\x04R\x03num\x12\x12\n" +
	"\x04path\x18\x02 \x01(\fR\x04path\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x14\n" +
	"\x05inbox\x18\x04 \x01(\fR\x05inbox\"r\n" +
	"\bSubFrame\x12\x10\n" +
	"\x03num\x18\x01 \x01(\x04R\x03num\x12\x12\n" +
	"\x04path\x18\x02 \x01(\fR\x04path\x12\x14\n" +
	"\x05group\x18\x03 \x01(\fR\x05group\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x03R\x05limit\x12\x14\n" +
	"\x05flags\x18\x05 \x01(\x04R\x05flags\"\x1e\n" +
	"\n" +
	"UnsubFrame\x12\x10\n" +
	"\x03num\x18\x01 \x01(\x04R\x03num\"7\n" +
	"\vStatusFrame\x12\x10\n" +
	"\x03num\x18\x01 \x01(\x04R\x03num\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x04R\x06statusB\x11Z\x0fyat.io/yat/wireb\x06proto3"

var (
	file_frames_proto_rawDescOnce sync.Once
	file_frames_proto_rawDescData []byte
)

func file_frames_proto_rawDescGZIP() []byte {
	file_frames_proto_rawDescOnce.Do(func() {
		file_frames_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_frames_proto_rawDesc), len(file_frames_proto_rawDesc)))
	})
	return file_frames_proto_rawDescData
}

var file_frames_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_frames_proto_goTypes = []any{
	(*Msg)(nil),         // 0: yat.Msg
	(*SubFrame)(nil),    // 1: yat.SubFrame
	(*UnsubFrame)(nil),  // 2: yat.UnsubFrame
	(*StatusFrame)(nil), // 3: yat.StatusFrame
}
var file_frames_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_frames_proto_init() }
func file_frames_proto_init() {
	if File_frames_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_frames_proto_rawDesc), len(file_frames_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_frames_proto_goTypes,
		DependencyIndexes: file_frames_proto_depIdxs,
		MessageInfos:      file_frames_proto_msgTypes,
	}.Build()
	File_frames_proto = out.File
	file_frames_proto_goTypes = nil
	file_frames_proto_depIdxs = nil
}
